version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    restart: always
    command: >
      bash -c "cd /app &&
               rm -f database.db &&
               python app.py"